"""Narrow label-access migration: rebuild ONLY ``label_access.csv`` and the label-access metadata in
``data/logs/splits.json``, from the already-frozen canonical ``assignments.csv``.

This exists because the split-regime generator cannot express "regenerate the derived label-access
artifacts". It reconstructs partitions from scratch and rewrites every ``assignments.csv``, which is a
split-MEMBERSHIP regeneration -- exactly what must not happen once the assignments are canonical. Even
a byte-identical rewrite is the wrong operation: it re-derives frozen scientific inputs from live code
and data, so the frozen tree would only stay correct by coincidence.

This tool instead treats the assignments as the immutable source of truth:

* populations (``source_train`` / ``target_label_pool`` / ``target_test``) are READ from the frozen
  assignments rows, never re-partitioned;
* the benchmark pickle supplies class metadata for the allocation audit ONLY -- never membership;
* it computes the nested ``source_rank`` / ``target_rank``, the benchmark budget ``B_d``, and
  region-level eligibility through the SAME shared pass the generator uses
  (:func:`evals.label_access.finalize`), so the two cannot drift apart;
* it imports no assignments writer and never invokes regime split generation, so it CANNOT write an
  ``assignments.csv`` -- a regression test pins that by making the writer raise on contact.

``splits.json`` keeps the ORIGINAL assignment-generation provenance untouched and gains a separate
``label_access_provenance`` block, because the old assignments were emphatically not generated by this
revision and the log must not claim they were. It is written LAST, after every new artifact is
constructed and validated, so a failure part-way leaves the canonical log intact.

No command-line arguments: edit the CONFIG block below and run it.

    python tools/migrate_label_access.py
"""

from __future__ import annotations

import os
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

_SRC = Path(__file__).resolve().parents[1] / "src"
_REPO = Path(__file__).resolve().parents[1]
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from evals import evals as EV  # noqa: E402
from evals import label_access as _LA  # noqa: E402  (shared region-level finalize)
from evals import split_artifacts as SA  # noqa: E402
from utils import cacheutils  # noqa: E402  (benchmark loader only)

# === Configuration ===========================================================
SPLITS_ROOT = cacheutils.SCRATCH / "splits"          # data/splits/
LOGS_PATH = SA.default_log_path(SPLITS_ROOT)          # data/logs/splits.json
BENCHMARKS = ["cropharvest", "eurocropsml", "breizhcrops", "pastis"]
DRY_RUN = True    # True = build + validate + report, write nothing. False = publish.
# =============================================================================

_SOURCE_TRAIN = "source_train"
_TARGET_POOL = "target_label_pool"
_TARGET_TEST = "target_test"


def _populations(root: Path, entry: dict) -> dict[str, list[str]]:
    """The three label-access populations for one leaf, READ from its frozen assignments.csv.

    Only ``status == assigned`` rows are populations; purged and excluded rows were deliberately
    removed from the experiment and must never re-enter through a derived artifact.
    """
    path = Path(root) / entry["assignments_csv"]
    if not path.is_file():
        raise SA.SplitArtifactError(f"missing canonical assignments.csv at {path}")
    out: dict[str, list[str]] = {_SOURCE_TRAIN: [], _TARGET_POOL: [], _TARGET_TEST: []}
    for r in SA.read_assignments_csv(path):
        if r["status"] != SA.STATUS_ASSIGNED:
            continue
        if r["partition"] in out:
            out[r["partition"]].append(r["stable_id"])
    return out


def _class_map(benchmark: str) -> dict[str, frozenset[str]]:
    """stable_id -> class set, for the allocation audit ONLY.

    Tabular ids map to a singleton label; dense PASTIS patch ids map to the patch's whole class set,
    because a patch is allocated whole and contributes every class it contains.
    """
    bench_mod = EV.load_benchmark(benchmark)
    bench = cacheutils.cached_bench(bench_mod.BENCHMARK)
    if getattr(bench_mod, "LABEL_KIND", "") == "segmentation":
        patch_ids = [int(p) for p in bench.patch_ids(None)]
        sets = bench.patch_class_sets(patch_ids)
        return {str(int(p)): frozenset(str(c) for c in sets.get(int(p), ())) for p in patch_ids}
    y, _groups = bench_mod.make_targets(bench)
    sample_ids = bench.sample_ids
    return {str(sample_ids[i]): frozenset({str(y[i])}) for i in range(len(sample_ids))}


def _candidates(root: Path, benchmark: str, entries: list[dict]) -> list[dict]:
    """Label-access candidates for one benchmark, built entirely from frozen artifacts."""
    geo = [
        e for e in entries
        if e["benchmark"] == benchmark and e["regime"] == SA.LABEL_ACCESS_REGIME
        and e.get("supports_target_labels")
    ]
    if not geo:
        return []
    classes = _class_map(benchmark)
    out: list[dict] = []
    for e in sorted(geo, key=lambda e: (str(e["holdout"]), int(e["seed"]))):
        pops = _populations(root, e)
        ids = [*pops[_SOURCE_TRAIN], *pops[_TARGET_POOL]]
        missing = [i for i in ids if i not in classes]
        if missing:
            raise SA.SplitArtifactError(
                f"{benchmark}/{e['holdout']}/seed={e['seed']}: {len(missing)} assigned id(s) absent from "
                f"the benchmark pickle (e.g. {missing[:5]}) -- the frozen split and the staged data disagree"
            )
        out.append({
            "seed": int(e["seed"]), "holdout": str(e["holdout"]),
            "source_ids": pops[_SOURCE_TRAIN], "pool_ids": pops[_TARGET_POOL],
            "test_ids": pops[_TARGET_TEST],
            "n_source": len(pops[_SOURCE_TRAIN]), "n_target_pool": len(pops[_TARGET_POOL]),
            "class_of": {i: classes[i] for i in ids},
            "summary": e,   # finalize() patches the label-access block onto the live log entry
        })
    return out


def _code_revision() -> str:
    try:
        return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=_REPO, text=True).strip()
    except Exception:  # noqa: BLE001 -- provenance best-effort; never block the migration
        return "unknown"


def _tree_is_dirty() -> str:
    try:
        out = subprocess.check_output(["git", "status", "--porcelain"], cwd=_REPO, text=True)
    except Exception:  # noqa: BLE001 -- cannot prove clean; treat as dirty
        return "git status unavailable"
    dirty = [ln for ln in out.splitlines() if ln[3:].startswith(("src/", "tools/"))]
    return "; ".join(sorted(ln.strip() for ln in dirty)[:8])


def main() -> int:
    root = Path(SPLITS_ROOT)
    log = SA.read_splits_log(LOGS_PATH)
    entries: list[dict] = log["leaves"]
    mode = "DRY RUN (nothing written)" if DRY_RUN else f"PUBLISH -> {root} + {LOGS_PATH}"
    print(f"[migrate_label_access] {mode}", flush=True)
    if not DRY_RUN:
        dirty = _tree_is_dirty()
        if dirty:
            raise SystemExit(
                "[migrate_label_access] REFUSING to publish: src/ or tools/ has uncommitted changes, so "
                f"the recorded label-access revision ({_code_revision()[:12]}) would not contain the code "
                f"that produced these artifacts.\n  dirty: {dirty}"
            )

    before = {e["holdout"] + "/" + str(e["seed"]) for e in entries if e.get("label_access_csv")}
    for benchmark in BENCHMARKS:
        cands = _candidates(root, benchmark, entries)
        if not cands:
            print(f"  {benchmark}: no label-access leaves", flush=True)
            continue
        # Every region is built and validated before ANY file is written (finalize stages first).
        _LA.finalize(root, benchmark, cands, audit_only=DRY_RUN)

    # A region that is no longer allocation-eligible must not keep a stale frozen order on disk or a
    # stale pointer in the log -- a reader would otherwise consume an order for an excluded region.
    stale = 0
    for e in entries:
        la = e.get("label_access", {})
        if la.get("excluded") and e.get("label_access_csv"):
            path = root / e["label_access_csv"]
            if not DRY_RUN and path.is_file():
                path.unlink()
            e.pop("label_access_csv", None)
            e.pop("label_access_sha256", None)
            stale += 1
    after = {e["holdout"] + "/" + str(e["seed"]) for e in entries if e.get("label_access_csv")}
    print(f"  label-access leaves: {len(before)} -> {len(after)} ({stale} stale removed)", flush=True)

    if DRY_RUN:
        print("[migrate_label_access] DRY RUN complete -- no artifact or log was written.", flush=True)
        return 0

    # The log is written LAST, after every artifact exists, and keeps the ORIGINAL assignment
    # provenance: those splits were not produced by this revision and the log must not say they were.
    provenance = {k: v for k, v in log.items() if k != "leaves"}
    provenance["label_access_provenance"] = {
        "code_revision": _code_revision(),
        "generation_timestamp": datetime.now(UTC).isoformat(timespec="seconds"),
        "data_fingerprint": os.environ.get("DATA_FINGERPRINT") or None,
        "derived_from_assignments": True,
        "assignments_regenerated": False,
        "allocation_percents": list(SA.ALLOCATION_PERCENTS),
        "additive_counts": list(SA.LABEL_ACCESS_COUNTS),
        "min_headline_targets": int(SA.MIN_HEADLINE_TARGETS),
    }
    SA.write_splits_log(LOGS_PATH, provenance=provenance, entries=entries)
    print(f"[migrate_label_access] wrote {LOGS_PATH}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
